# Generated by Django 5.0.4 on 2024-04-29 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Father_Name',
            field=models.TextField(default='Alamgir'),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(default='Noakhali'),
        ),
    ]
